/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package revmanhalcochranemode;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Reader;
import java.io.Writer;
import java.nio.channels.FileChannel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.
        TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;


/**
 *
 * @author msabs1
 */
public class FrameMethods extends javax.swing.JFrame {

    private String path;
    private Vector vAllReferences = new Vector();
    private Complex1 cleaner = new Complex1(null);
    private boolean noChild = true;
    private boolean tagAppend = false;
    private Element subsectionTemp;
    private Element paragraphTemp;
    private Element headingTemp;
    private Element headingTemp2;
    private Element italicTemp;
    private Element subsectionTemp2;
    private boolean btnPressed=false;
    
    private File openTextfile;
    
    private String pathTXT =""; 
    /**
     * Creates new form FrameMethods
     */
    public FrameMethods(String p) 
    {
        initComponents();
        path=p;
        this.setTitle("RevMan Hal - Protocol - Methods");
        this.setLocation(300, 150);
        jPanel1.setBackground(new Color(226,226,226));
        this.setBackground(new Color(226,226,226));
        this.run();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_return = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taText = new javax.swing.JTextArea();
        btnOpen = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btn_exit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/revmanhalcochranemode/hal.png"))); // NOI18N

        btn_return.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/revmanhalcochranemode/back.png"))); // NOI18N
        btn_return.setText(" BACK");
        btn_return.setToolTipText("");
        btn_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_returnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 33)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 249));
        jLabel2.setText("RevMan HAL ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setText("Methods");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("<html><body>In this frame you are able to add the \"Methods\"-text to your RevMan file. You can see the text which will be added in the text area below. If you want to change anything press on \"Open Textfile\" and edit the file like you want. After saving the file you just need to press \"Refresh\" and the text will be reloaded.</body></html>");

        taText.setColumns(20);
        taText.setRows(5);
        jScrollPane1.setViewportView(taText);

        btnOpen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/revmanhalcochranemode/TxtFileSmall.png"))); // NOI18N
        btnOpen.setText("Open Textfile");
        btnOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenMouseClicked(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/revmanhalcochranemode/AddBtnSmall.png"))); // NOI18N
        btnAdd.setText(" ADD");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/revmanhalcochranemode/refreshSmall.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });

        btn_exit1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/revmanhalcochranemode/exit.png"))); // NOI18N
        btn_exit1.setText("EXIT");
        btn_exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOpen)
                        .addGap(30, 30, 30)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(147, 147, 147)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_exit1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(161, 161, 161)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit1))
                .addGap(30, 30, 30))
        );

        jLabel4.getAccessibleContext().setAccessibleName("<html><body>In this frame you are able to add the \"Methods\" to your RevMan file. You can see the added text in the text area below. <p></p>  If you want to change anything and save it afterwards, press the button \"Save to Text File\". Otherwise just press \"Add\" and the text will be added to the RevMan file without saving the changes.</body></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_returnMouseClicked
        // TODO add your handling code here:
           this.dispose();
        FrameProtocol frame = new FrameProtocol(path);
        frame.setVisible(true);
        frame.validate();
      
        
    }//GEN-LAST:event_btn_returnMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        
        if(btnPressed==true)
        {
             JOptionPane.showMessageDialog(this, "You can only press the button once","Clue", JOptionPane.WARNING_MESSAGE);  
        }
        
        if(taText.getText().isEmpty())
        {
        
        }
        else if(btnPressed==false)
        {
            btnPressed=true;
        
         SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
         Date currentTime = new Date();
        
        
        String filepath = path;            // REVMAN FILE
        Document doc = getDocument(filepath);     
        
        

        String[] arAllText = taText.getText().toString().split("\n");
        
        Node tag = null;        
        Node one = doc.getElementsByTagName("CRIT_OUTCOMES_PRIMARY").item(0);
        Node two = doc.getElementsByTagName("CRIT_OUTCOMES_SECONDARY").item(0);
        boolean secondSubsection;

        System.out.println("in add, vor for");
        
        for (int m = 0; m <arAllText.length ; m++) 
        {         
            secondSubsection = false;
            
            if(arAllText[m].trim().isEmpty())
            {
        
            }
            else
            {
            
        System.out.println("text, array: "+m +" "+ arAllText[m]);    
        try
        {
        System.out.println("sub: "+arAllText[m].trim().substring(4,arAllText[m].length()-4).trim());
        }
        catch(Exception e)
        {
        
        }
//           System.out.println("sub: "+arAllText[m].trim().substring(4,arAllText[m].length()-4).trim());
           
        System.out.println(m+ " after the catch");
        
        if(arAllText[m].trim().length()>8)
        {
        
            if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Background") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Background") )
            {
                System.out.println("in background!");
                 tag= doc.getElementsByTagName("BACKGROUND").item(0);  //SEARCH THE DOCUMENT FOR THE TAG NAME
                tagAppend = true;
                try
                {
                    Element child = (Element)tag.getLastChild();
                }
                catch(Exception e)
                {
                  noChild = true;
                }
                
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
                
                
            }     
              
                
                
                
          //      paragraph = doc.createElement("P");   // ADD TEXT (TEXT CAN ONLY BE ADDED IN P; MARKER IS PART OF PARAGRAPG3; PARAGRAPH3 IS PART OF INTERVENTION; INTERVENTION IS MAIN NODE)    
         //       Element marker = doc.createElement("MARKER");   // MARKER IS NEEDED TO ADD TEXT)
           //     marker.appendChild(doc.createTextNode("*------ Start of HAL generated text " + formatter.format(currentTime) + " ------* "));
          //      paragraph.appendChild(marker);
          //      tag.appendChild(paragraph);
                
             
            
            
            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Description of the condition") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Description of the condition"))
            {
                
                tag= doc.getElementsByTagName("CONDITION").item(0);  //SEARCH THE DOCUMENT FOR THE TAG NAME
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
               
            }
           
            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Description of the intervention") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Description of the intervention"))
            {
                 tag = doc.getElementsByTagName("INTERVENTION").item(0); 
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }
            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("How the intervention might work") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("How the intervention might work"))
            {
                    tag = doc.getElementsByTagName("THEORY").item(0); 
                    tagAppend = true;
                    subsectionTemp = doc.createElement("SUBSECTION");
                    subsectionTemp2 = doc.createElement("SUBSECTION");
                    paragraphTemp = doc.createElement("PARAGRAPH");
                    headingTemp = doc.createElement("HEADING");
                    headingTemp2 = doc.createElement("HEADING");
                    italicTemp = doc.createElement("ITALIC");
            }
              
            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Why it is important to do this review") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Why it is important to do this review"))
            {
                tag = doc.getElementsByTagName("IMPORTANCE").item(0); 
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }
            
            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Objectives") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Objectives"))
            {
                tag = doc.getElementsByTagName("OBJECTIVES").item(0);   //SEE EXAMPLE...
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }            
         
            
           
            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Types of studies") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Types of studies"))
            {
                tag = doc.getElementsByTagName("CRIT_STUDIES").item(0);   //All relevant randomised...
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }
            
            else if (arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Types of participants") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Types of participants"))
            {
                
                tag = doc.getElementsByTagName("CRIT_PARTICIPANTS").item(0);   //Adults, however
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }
            
            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Types of interventions") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Types of interventions"))
            {
                
                tag = doc.getElementsByTagName("CRIT_INTERVENTIONS").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }     
            
            
          else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Types of outcome measures") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Types of outcome measures"))
            {
                 
                 tag = doc.getElementsByTagName("CRIT_OUTCOMES").item(0);   //All outcomes will...                 
                 tag.removeChild(one);
                 tag.removeChild(two);
                 tagAppend = true;
                 subsectionTemp = doc.createElement("SUBSECTION");
                 subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
                
            }
             else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Primary outcomes") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Primary outcomes"))
            {
                
                tag.appendChild(one);
                tag.appendChild(two);
                tag = doc.getElementsByTagName("CRIT_OUTCOMES_PRIMARY").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }
             else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Secondary outcomes") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Secondary outcomes"))
            {
                
                tag = doc.getElementsByTagName("CRIT_OUTCOMES_SECONDARY").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }
                    
            
           if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Electronic searches") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Electronic searches"))
            {
                tag = doc.getElementsByTagName("ELECTRONIC_SEARCHES").item(0);   //LEAVE BLANK FOR..
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }
            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Searching other resources") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Searching other resources"))
            {
                
                tag = doc.getElementsByTagName("OTHER_SEARCHES").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }
            
            
            else if (arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Data collection and analysis") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Data collection and analysis"))// MUST BE COMPLETED..
            {
                System.out.println("IN DATA COLLECTION");
                
                tag = doc.getElementsByTagName("STUDY_SELECTION").item(0);
               tagAppend = true;
               subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }
            else if (arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Data extraction and management") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Data extraction and management"))// MUST BE COMPLETED..
            {
                System.out.println ("Data extraction: "+arAllText[m+1]);
                tag = doc.getElementsByTagName("DATA_EXTRACTION").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
               

            } else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Assessment of risk of bias in included studies") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Assessment of risk of bias in included studies"))// Assessment of risk...
            {

                tag = doc.getElementsByTagName("QUALITY_ASSESSMENT").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
               

            } 
            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Measures of treatment effect") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Measures of treatment effect"))// measures of treatment...
            {

                tag = doc.getElementsByTagName("EFFECT_MEASURES").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            } 
            else if (arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Unit of analysis issues") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Unit of analysis issues"))// unit of analsis...
            {

                tag = doc.getElementsByTagName("UNIT_OF_ANALYSIS").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");

            } else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Dealing with missing data") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Dealing with missing data"))// dealing with missing data...
            {

                tag = doc.getElementsByTagName("MISSING_DATA").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
               
            } else if (arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Assessment of heterogeneity") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Assessment of heterogeneity"))// assessment of heterogeneity...
            {

                tag = doc.getElementsByTagName("HETEROGENEITY_ASSESSMENT").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
                
            } else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Acknowledgements") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Acknowledgements"))// MUST BE COMPLETED..
            {
                
                
                Attr attr = doc.createAttribute("NOTES");
                String tempNotes = "<html><body><b>Acknowledgements</b><p>"
                +"[fixed, level 1 heading]<p>"
                +"This section should be used to acknowledge any people or organizations that the authors wish to acknowledge, including people who are not listed among the authors." 
                +"This would include any previous authors of the Cochrane review or previous sources of support to the review, and might include the contributions of the editorial team of the CRG." 
                +"Permission should be obtained from persons acknowledged.</body></html>";
                
                
                tag = doc.getElementsByTagName("ACKNOWLEDGEMENTS").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
                  attr.setValue(tempNotes);  
                 Element ackn = (Element)doc.getElementsByTagName("ACKNOWLEDGEMENTS").item(0);               
                 ackn.setAttributeNode(attr);
               
            } else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Contributions of authors") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Contributions of authors"))// MUST BE COMPLETED..
            {
                
                
                Attr attr = doc.createAttribute("NOTES");
                String tempNotes = "<html><body><b>Contributions of authors</b>\n" +
"[fixed, level 1 heading]\n" +
"The contributions of the current co-authors to the protocol or review should be described in this section. One author should be identified as the guarantor of the review. All authors should discuss and agree on their respective descriptions of contribution before the review is submitted for publication on the CDSR. When the review is updated, this section should be checked and revised as necessary to ensure that it is accurate and up to date.\n" +

"The following potential contributions have been adapted from Yank et al. (Yank 1999). This is a suggested scheme and the section should describe what people did, rather than attempt to identify which of these categories someone’s contribution falls within. Ideally, the authors should describe their contribution in their own words." +
"<ul><li>Conceiving the review.</li>" +
"<li>Designing the review.</li>" +
"<li>Coordinating the review.</li>" +
"<li>Data collection for the review.</li>" +
"<li>Designing search strategies.</li>" +
"<li>Undertaking searches.</li>" +
"<li>Screening search results.</li>" +
"<li>Organizing retrieval of papers.</li>" +
"<li>Screening retrieved papers against eligibility criteria.</li>" +
"<li>Appraising quality of papers.</li>" +
"<li>Extracting data from papers.</li>" +
"<li>Writing to authors of papers for additional information.</li>" +
"<li>Providing additional data about papers.</li>" +
"<li>Obtaining and screening data on unpublished studies.</li>" +
"<li>Data management for the review.</li>" +
"<li>Entering data into RevMan.</li>" +
"<li>Analysis of data.</li>" +
"<li>Interpretation of data.</li>" +
"<li>Providing a methodological perspective.</li>" +
"<li>Providing a clinical perspective.</li>" +
"<li>Providing a policy perspective.</li>" +
"<li>Providing a consumer perspective.</li>" +
"<li>Writing the review (or protocol).</li>" +
"<li>Providing general advice on the review.</li>" +
"<li>Securing funding for the review.</li>" +
"<li>Performing previous work that was the foundation of the current review.</li></ul></body></html>";
                
                tempNotes = tempNotes.replaceAll("\n", "<p>");
                
               
            
                
              
                
                
               tag = doc.getElementsByTagName("CONTRIBUTIONS").item(0);
               tagAppend = true;
               subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
                 attr.setValue(tempNotes);                 
               Element contrib = (Element)doc.getElementsByTagName("CONTRIBUTIONS").item(0);
               contrib.setAttributeNode(attr);
               
            } else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Declarations of interest") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Declarations of interest"))// MUST BE COMPLETED..
            {
                
                Attr attr = doc.createAttribute("NOTES");
                String tempNotes = "<html><body><b>Declarations of interest</b>\n" +
                "[fixed, level 1 heading]\n" +
                "Authors should report any present or past affiliations or other involvement in any organization or entity with an interest in the review that might lead to a real or perceived conflict of interest. Situations that might be perceived by others as being capable of influencing a review author’s judgements include personal, political, academic and other possible conflicts, as well as financial conflicts. Authors must state if they have been involved in a study included in the review. \n" +
                "<I>See also</I>" +
                "<ul><li>A summary of the Collaboration’s policy on conflicts of interest appears in Chapter <u>2</u> (Section <u>2.6</u>).</li></ul>\n" +
                "Financial conflicts of interest cause the most concern, and should be avoided, but must be reported if there are any. Any secondary interest (such as personal conflicts) that might unduly influence judgements made in a review (concerning, for example, the inclusion or exclusion of studies, assessments of the validity of included studies or the interpretation of results) should be reported.\n" +
                "If there are no known conflicts of interest, this should be stated explicitly, for example, by writing ‘None known’.</body></html>";
                
                tempNotes = tempNotes.replaceAll("\n", "<p>");
                
                tag = doc.getElementsByTagName("CONFLICT_OF_INTEREST").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
                attr.setValue(tempNotes);                 
                Element contrib = (Element)doc.getElementsByTagName("CONFLICT_OF_INTEREST").item(0);
                contrib.setAttributeNode(attr);
            }


            // .. bennys code end


            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Assessment of reporting biases") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Assessment of reporting biases"))
            {

                tag = doc.getElementsByTagName("BIAS_ASSESSMENT").item(0);
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }

            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Data synthesis") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Data synthesis"))
            {
                tag = doc.getElementsByTagName("DATA_SYNTHESIS").item(0);   //We understand that...
                tagAppend = true;
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");
            }


            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Subgroup analysis and investigation of heterogeneity") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Subgroup analysis and investigation of heterogeneity"))
            {
                    
                if(arAllText[m].trim().substring(0,2).equals("--"))
                {
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");        
                tag = doc.getElementsByTagName("SUBGROUP_ANALYSIS").item(0);
                tagAppend = true;  
                }
            }

            else if(arAllText[m].trim().substring(4,arAllText[m].length()-4).trim().equalsIgnoreCase("Sensitivity analysis") 
                    ||arAllText[m].trim().substring(5,arAllText[m].length()-4).trim().equalsIgnoreCase("Sensitivity analysis"))
            {
                subsectionTemp = doc.createElement("SUBSECTION");
                subsectionTemp2 = doc.createElement("SUBSECTION");
                paragraphTemp = doc.createElement("PARAGRAPH");
                headingTemp = doc.createElement("HEADING");
                headingTemp2 = doc.createElement("HEADING");
                italicTemp = doc.createElement("ITALIC");

                tag = doc.getElementsByTagName("SENSITIVITY_ANALYSIS").item(0);
                tagAppend = true;
             

            }

        }
        
               try
                {
                    Element child = (Element)tag.getLastChild();
                    if(child.getTextContent().toString().equals(""))
                    {
                        noChild = true;
                    }
                }
                catch(Exception e)
                {
                  noChild = true;
                }
               
        
       //        System.out.println("This is tag: "+tag.toString() + " "+m +" sub: "+arAllText[m].trim().substring(0,2));
  
            
            if (arAllText[m].trim().length()>3&&arAllText[m].trim().substring(0,3).equalsIgnoreCase("RT:"))
            {
                
                String author="";
                String type ="";
                boolean checkIdentifier = false;
                  tag = doc.getElementsByTagName("ADDITIONAL_REFERENCES").item(0);
                Element reference = doc.createElement("REFERENCE");
                
                
                tag.appendChild(reference);
                 
                for(int p=3;p<arAllText[m+1].length();p++)
                    {
                        if(arAllText[m+1].substring(p,p+1).equals(" "))
                        {
                            break;
                        }
                        else
                        {
                            author=author+arAllText[m+1].substring(p,p+1);
                        }
                    }
               
                
                int year =0;
                if(arAllText[m+3].substring(3,4).equals("1") || arAllText[m+3].substring(3,4).equals("2"))
                {
                    year = 3;
                }
                else if(arAllText[m+4].substring(3,4).equals("1") || arAllText[m+4].substring(3,4).equals("2"))
                {
                    year =4;                    
                }
                else
                {
                    year = 5;
                }
               System.out.println("this is the year: "+year + " "+ arAllText[m+3]);
                
                String stReference="REF-"+author+"-"+arAllText[m+year].substring(3,7);
                String stName = author+" "+arAllText[m+year].substring(3,7);
                
                
                for(int w = 0;w<vAllReferences.size();w++)   
                {
                     if(vAllReferences.elementAt(w).toString().equals(stReference))
                     {
                         stReference= stReference+"a";
                         stName = stName+"a";
                     }
                }
                
                System.out.println("stName: "+stName+" st Ref: "+stReference);
                
                     Attr attr = doc.createAttribute("ID");
                     attr.setValue(stReference);
                     reference.setAttributeNode(attr);
                     
                     vAllReferences.addElement("REF-"+author+"-"+arAllText[m+year].substring(3,7));
                     
                     Attr attr2 = doc.createAttribute("NAME");
                     attr2.setValue(stName);
                     reference.setAttributeNode(attr2);
                     
                     Attr attr3 = doc.createAttribute("TYPE");
                     if(arAllText[m].substring(3,arAllText[m].length()).equalsIgnoreCase("Conference proceedings"))
                     {
                         type = "CONFERENCE_PROC";
                     }
                     else if(arAllText[m].substring(3,arAllText[m].length()).equalsIgnoreCase("Journal article"))
                     {
                         type = "JOURNAL_ARTICLE";
                     }
                     else if(arAllText[m].substring(3,arAllText[m].length()).equalsIgnoreCase("Section of Book")||arAllText[m].substring(3,arAllText[m].length()).equalsIgnoreCase("Book"))
                     {
                         type = "BOOK_SECTION";
                     }
                      else if(arAllText[m].substring(3,arAllText[m].length()).equalsIgnoreCase("Other"))
                     {
                         type = "OTHER";
                     }                     
                     
                     attr3.setValue(type);
                     reference.setAttributeNode(attr3);
                
                for(int o=m+1;o<arAllText.length;o++)
                {
                     if(arAllText[o].equals("")||o==arAllText.length-1)
                       {
                           
                           if(checkIdentifier==true)
                           {
                               
                           }
                           else
                           {
                               Element identifier = doc.createElement("IDENTIFIERS");
                               reference.appendChild(identifier);
                               System.out.println("in else identifiers");
                           }
                           System.out.println("in break dinna");
                           m = o;
                           break;
                        }
                    
                      if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("AU:"))
                      {
                          Element au = doc.createElement("AU");
                          au.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(au);
                      }
                      else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("TI:"))
                      {
                          Element ti = doc.createElement("TI");
                          ti.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(ti);
                      }
                      else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("TO:"))
                      {
                          Element to = doc.createElement("TO");
                          to.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(to);
                      }
                      else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("SO:"))
                      {
                          Element so = doc.createElement("SO");
                          so.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(so);
                      }
                      else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("YR:"))
                      {
                          Element yr = doc.createElement("YR");
                          yr.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(yr);
                      }
                      else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("PB:"))
                      {
                          Element pb = doc.createElement("PB");
                          pb.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(pb);
                      }
                       else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("CY:"))
                      {
                          Element cy = doc.createElement("CY");
                          cy.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(cy);
                      }
                      else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("VL:"))
                      {
                          Element vl = doc.createElement("VL");
                          vl.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(vl);
                      }
                      else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("NO:"))
                      {
                          Element no = doc.createElement("NO");
                          no.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(no);
                      }
                      else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("PG:"))
                      {
                          Element pg = doc.createElement("PG");
                          pg.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(pg);
                      }
                      else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("ED:"))
                      {
                          Element ed = doc.createElement("ED");
                          ed.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(ed);
                      }
                       else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("MD:"))
                      {
                          Element md = doc.createElement("MD");
                          md.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(md);
                      }
                         else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("EN:"))
                      {
                          Element en = doc.createElement("EN");
                          en.appendChild(doc.createTextNode(arAllText[o].trim().substring(3,arAllText[o].length())));
                          reference.appendChild(en);
                      }
                    
                    
                      else if(arAllText[o].trim().substring(0,3).equalsIgnoreCase("ID:"))
                      {
                          Element identifiers = doc.createElement("IDENTIFIERS");
                          
                          Element identifier = doc.createElement("IDENTIFIER");
                          String typeID="";
                          
                          Attr attr4 = doc.createAttribute("TYPE");
                          Attr attr5 = doc.createAttribute("VALUE");                          
                          for (int p = 3; p < arAllText[o].length(); p++) 
                          {
                              if (arAllText[o].substring(p, p + 1).equals(" ")) 
                              {
                                  break;
                              } 
                              else 
                              {
                                  typeID = typeID + arAllText[o].substring(p, p + 1);
                              }
                          }
                          System.out.println("typeID: "+typeID);
                          
                          attr4.setValue(typeID);
                          attr5.setValue(arAllText[o].substring(typeID.length()+4, arAllText[o].length()));
                          identifier.setAttributeNode(attr4);
                          identifier.setAttributeNode(attr5);
                          identifiers.appendChild(identifier);
                          reference.appendChild(identifiers);
                          
                          checkIdentifier=true;
                      }
                   
                } 
            } 
             else if(arAllText[m].trim().substring(0, 2).equals("LR"))
                {
                    Element link = doc.createElement("LINK");
                    Attr attrLink1 = doc.createAttribute("REF");
                    Attr attrLink2 = doc.createAttribute("TYPE");
                    String stAttrLink1 = arAllText[m].substring(3,arAllText[m].length()).replaceAll(" ", "-");
                    attrLink1.setValue("REF-" + stAttrLink1);
                    attrLink2.setValue("REFERENCE");
                    link.setAttributeNode(attrLink1);
                    link.setAttributeNode(attrLink2);
                    link.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                    paragraphTemp.appendChild(link);                   
                }
             else if(arAllText[m].trim().substring(0, 2).equals("LI"))
                {
                    Element link3 = doc.createElement("A");
                    Attr attrLink4 = doc.createAttribute("HREF");              
                    attrLink4.setValue(arAllText[m].substring(arAllText[m].toString().indexOf(":")+1,arAllText[m].toString().length()).trim());         
                    link3.setAttributeNode(attrLink4);
                    link3.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].toString().indexOf(":"))));
                    paragraphTemp.appendChild(link3);                 
                }
              
              else if(arAllText[m].trim().substring(0, 2).equals("!!"))
                {
                    Element link = doc.createElement("LINK");
                    Attr attrLink5 = doc.createAttribute("TAG");
                    Attr attrLink6 = doc.createAttribute("TYPE");
                    attrLink5.setValue("SUBGROUP_ANALYSIS");
                    attrLink6.setValue("SECTION");
                    link.setAttributeNode(attrLink5);
                    link.setAttributeNode(attrLink6);
                
                    link.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                    paragraphTemp.appendChild(link);                    
                }
              else  if(arAllText[m].trim().substring(0, 2).equals("II"))
                {
                    Element italic = doc.createElement("I");
                    italic.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length())));
                    italicTemp = italic;
                    paragraphTemp.appendChild(italic);                      
                }
              else  if(arAllText[m].trim().substring(0, 2).equals("PP"))
                {   
                    if(noChild == true)
                    {      
                        System.out.println(tag.toString());
                    Element para = doc.createElement("P");
                    para.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                    tag.appendChild(para);
                       // ERROR MESSAGE!! 
                    paragraphTemp = para;
                    noChild = false;
                    }
                    else
                    {
                         
                        try
                        {
                        int temp = Integer.parseInt(headingTemp.getAttribute("LEVEL"));
                        int temp2 =Integer.parseInt(headingTemp2.getAttribute("LEVEL"));
                        
                        System.out.println("levels subs: "+ temp +" "+temp2);
                        
                        if(temp2>temp)
                        {
                        secondSubsection = true;
                        }
                        
                        }
                        catch(Exception e)
                        {
                            secondSubsection = false;
                        }
                    if(secondSubsection==true)
                    {
                        Element para = doc.createElement("P");
                        para.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                        subsectionTemp2.appendChild(para);
                        paragraphTemp = para;
                    }
                    else if(arAllText[m-1].trim().substring(0, 1).equalsIgnoreCase("H"))
                    {                       
                        Element para = doc.createElement("P");
                        para.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                        subsectionTemp.appendChild(para);
                        paragraphTemp = para;
                    }
                    else if(arAllText[m-1].trim().substring(0, 2).equalsIgnoreCase("PP"))
                    {                        
                        Element para = doc.createElement("P");
                        para.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                        
                        System.out.println("subsection " + subsectionTemp.getTextContent().toString());
                        if (subsectionTemp.getTextContent().toString().equals(""))
                        {
                            tag.appendChild(para);
                            System.out.println("in subsection dinna" + subsectionTemp);
                        }
                        else
                        {
                        subsectionTemp.appendChild(para);
                        }
                        paragraphTemp = para;
                    }
                    else if(arAllText[m-1].trim().substring(0, 2).equalsIgnoreCase("II"))
                    {
                        Element para = doc.createElement("P");
                        para.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                        tag.appendChild(para);
                        paragraphTemp = para;
                    }
                    else
                    {
                        System.out.println("django else");
                    Element p = (Element)tag.getLastChild();
                    Element para = doc.createElement("P");
                    para.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                    p.appendChild(para);
                    paragraphTemp = para;
                    
                       if(tagAppend == true)
                    {
                        tag.appendChild(p);
                        tagAppend = false;
                    }
                    }
                    }
                    
                }
              else if(arAllText[m].trim().substring(0, 2).equals("SP"))
                {   
                    paragraphTemp.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));                    
                }
                 
         /*   else if(arAllText[m].trim().substring(0, 2).equals("II"))
                {
                    Element p = (Element)tag.getLastChild();
                     if(arAllText[m+1].trim().substring(0, 2).equals("IB"))
                     {
                         Element bold = doc.createElement("B");
                          
                    Element italic = doc.createElement("I");
                    italic.appendChild(doc.createTextNode(arAllText[m ]));
                    bold.appendChild(doc.createTextNode(arAllText[m+1]));
                     italic.appendChild(bold);
                    p.appendChild(italic);
                  
                     }
                     else
                     {                         
                    Element italic = doc.createElement("I");
                    italic.appendChild(doc.createTextNode(arAllText[m ]));
                    
                    p.appendChild(italic);
                     }
                   
                    if(tagAppend == true)
                    {
                        tag.appendChild(p);
                        tagAppend = false;
                    }
                    
                }
           */
               else if(arAllText[m].trim().substring(0, 2).equals("BP"))
                {
                     Element bold = doc.createElement("B");                     
                    bold.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                    if(arAllText[m-1].trim().substring(0, 2).equalsIgnoreCase("II"))
                    {
                    italicTemp.appendChild(bold);
                    }
                    else
                    {
                    paragraphTemp.appendChild(bold); 
                    }
                  }
               
                else if(arAllText[m].trim().substring(0, 2).equals("SU"))
                  {
                    Element sup = doc.createElement("SUP");
                    sup.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                    paragraphTemp.appendChild(sup);
                    
                    
                                   
                  }
                else if(arAllText[m].trim().substring(0, 2).equals("BR"))
                  {
                    Element br = doc.createElement("BR");
                    paragraphTemp.appendChild(br);      
                    System.out.println("in BR dinna "+paragraphTemp.toString());
          
                  }
                else if(arAllText[m].trim().substring(0, 2).equals("H1"))
                  {
                     if(noChild == true||headingTemp.getAttribute("LEVEL").equals("1"))
                    {
                    Element subsection = doc.createElement("SUBSECTION");
                    Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("1");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    
                    subsectionTemp = subsection; 
                    headingTemp = heading;
                    
                    tag.appendChild(subsection);
                    
                    noChild = false;
                    }
                    else
                    {
                     Element subsection =doc.createElement("SUBSECTION");
                     Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("1");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    subsectionTemp2 = subsection;
                    headingTemp2 = heading;
                    subsectionTemp.appendChild(subsection);                
                    
                  }
                  }
                 else if(arAllText[m].trim().substring(0, 2).equals("H2"))
                  {
                     if(noChild == true||headingTemp.getAttribute("LEVEL").equals("2"))
                    {
                    Element subsection = doc.createElement("SUBSECTION");
                    Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("2");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    
                    subsectionTemp = subsection;  
                    headingTemp = heading;
                    
                    tag.appendChild(subsection);
                    
                    noChild = false;
                    }
                    else
                    {
                     Element subsection =doc.createElement("SUBSECTION");
                     Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("2");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    headingTemp2 = heading;
                    subsectionTemp2 = subsection;
                    subsectionTemp.appendChild(subsection);                
                    
                  }
                  }
                  
                  else if(arAllText[m].trim().substring(0, 2).equals("H3"))
                  {
                     if(noChild == true||headingTemp.getAttribute("LEVEL").equals("3"))
                    {
                    Element subsection = doc.createElement("SUBSECTION");
                    Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("3");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    tag.appendChild(subsection);
                    
                    subsectionTemp = subsection; 
                    headingTemp = heading;
                    
                    noChild = false;
                    }
                    else
                    {   
                     Element subsection =doc.createElement("SUBSECTION");
                     Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("3");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    headingTemp2 = heading;
                    subsectionTemp2 = subsection;
                   subsectionTemp.appendChild(subsection);                
                    
                  }
                  }
                   else if(arAllText[m].trim().substring(0, 2).equals("H4"))
                  {
                      System.out.println("getAttr: 4 "+headingTemp.getAttribute("LEVEL").toString());
                     if(noChild == true ||headingTemp.getAttribute("LEVEL").equals("4"))   // so there is no heading next
                    {
                    Element subsection = doc.createElement("SUBSECTION");
                    Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("4");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    
                    subsectionTemp = subsection;
                    headingTemp = heading;
                                        
                    tag.appendChild(subsection);
                    
                    noChild = false;
                    }            
                     else
                    {                       
                    
                     Element subsection =doc.createElement("SUBSECTION");
                     Element heading = doc.createElement("HEADING");
                     heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("4");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    headingTemp2 = heading;
                    subsectionTemp2 = subsection;
                    subsectionTemp.appendChild(subsection);                
                     }
                  }
                  
                    else if(arAllText[m].trim().substring(0, 2).equals("H5"))
                  {
                      System.out.println("getAttr: 5 "+headingTemp.getAttribute("LEVEL").toString());
                      if(noChild == true||headingTemp.getAttribute("LEVEL").equals("5"))
                    {
                    Element subsection = doc.createElement("SUBSECTION");
                    Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("5");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    subsectionTemp = subsection;
                    headingTemp = heading;
                    
                    tag.appendChild(subsection);
                    
                    noChild = false;
                    }
                    else
                    {
                      
                     Element subsection =doc.createElement("SUBSECTION");
                     Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("5");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    headingTemp2 = heading;
                    subsectionTemp2 = subsection;
                    subsectionTemp.appendChild(subsection);                
                    
                  }
                  }
                     else if(arAllText[m].trim().substring(0, 2).equals("H6"))
                  {
                                           
                     if(noChild == true||headingTemp.getAttribute("LEVEL").equals("6"))
                    {
                    Element subsection = doc.createElement("SUBSECTION");
                    Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("6");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    
                    headingTemp = heading;
                    
                    subsectionTemp = subsection;
                    tag.appendChild(subsection);
                    
                    noChild = false;
                    }
                    else
                    {
                     Element subsection =doc.createElement("SUBSECTION");
                     Element heading = doc.createElement("HEADING");
                    heading.appendChild(doc.createTextNode(arAllText[m].substring(2,arAllText[m].length()))); 

                    Attr attr = doc.createAttribute("LEVEL");
                    attr.setValue("6");
                    heading.setAttributeNode(attr);
                    subsection.appendChild(heading);
                    headingTemp2 = heading;
                    subsectionTemp2 = subsection;
                    subsectionTemp.appendChild(subsection);                
                    
                  }
                  }
                else if(arAllText[m].trim().substring(0, 2).equals("SH"))
                {              
                    System.out.println("in heading dinna!");
                    if(arAllText[m].trim().contains("2"))
                    {
                    Element sup = doc.createElement("SUP");
                    sup.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));
                    headingTemp2.appendChild(sup);             
                    }
                    else
                    {
                     headingTemp2.appendChild(doc.createTextNode(arAllText[m].substring(3,arAllText[m].length())));  
                    }
                    
                }
            
        }
        }
           
             try 
             {
                  TransformerFactory transformerFactory = TransformerFactory.newInstance();
                 Transformer transformer;

                 transformer = transformerFactory.newTransformer();
                 DOMSource source = new DOMSource(doc);
                 StreamResult result = new StreamResult(new File(filepath));   // THE SOLUTION FOR UMLAUTS????!?!?!
                 transformer.transform(source, result);
                 
                 cleaner.deleteSpecialChars(filepath);
                 
                JOptionPane.showMessageDialog(this, "The text was added successfully to your RevMan File","Clue", JOptionPane.WARNING_MESSAGE);  
                 
             } 
             catch (Exception e) 
             {
                 JOptionPane.showMessageDialog(this, "Error in adding the text: "+e.toString(),"ERROR", JOptionPane.ERROR_MESSAGE);  
             }
           
           
            
            
             btnAdd.setEnabled(false);
            
        }
        
       
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenMouseClicked
        
    
        
        File openTXT = new File(pathTXT);

        Desktop openTXT2 = null;
        if (Desktop.isDesktopSupported()) {
            openTXT2 = Desktop.getDesktop();
        }
        try {
            openTXT2.open(openTXT);
        } catch (Exception e) {
            final JOptionPane pane = new JOptionPane("Error in opening the .txt file! Error message: "+e.toString());
             final JDialog d = pane.createDialog(null, "ERROR");
             d.setLocation(450, 430);
             d.setVisible(true);
            
        }

     
    }//GEN-LAST:event_btnOpenMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
       
        this.dispose();
        FrameMethods start = new FrameMethods(path);
        start.setVisible(true);
        start.validate();
   
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btn_exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exit1MouseClicked
             int resultBeenden = JOptionPane.showConfirmDialog(this, "Do you really want to end the program?", "EXIT", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resultBeenden==JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exit1MouseClicked

    public void run()
    {
     
        
        try   
        {           

                    StringBuffer sbAllText = new StringBuffer();

                    pathTXT = System.getProperty("user.dir");
                                      

                   pathTXT = pathTXT  +"\\Methods.txt";  //for final version!!!!
                    
                //    pathTXT = pathTXT +"\\src\\revmanhalcochranemode\\MethodsText.txt"; 
                    
                    System.out.println("das ist pfad "+pathTXT);
                     Reader fr = new InputStreamReader(new FileInputStream(pathTXT), "UTF-8");
                    BufferedReader br = new BufferedReader(fr);

                    int counter = 0;
                    String newLine = br.readLine();

                    while(newLine!=null)
                    {
                        taText.setText(taText.getText()+newLine+"\n");
                        System.out.println("line: "+counter+" "+newLine+"\n");
                        counter = counter+1;
                        newLine = br.readLine();
                    }
                   
                    br.close();
                    
                    
                    taText.setCaretPosition(0);
                    

             }
        
        catch(Exception e)
        {
            final JOptionPane pane = new JOptionPane("Error in reading the .txt file! Error message: "+e.toString());
             final JDialog d = pane.createDialog(null, "ERROR");
             d.setLocation(450, 430);
             d.setVisible(true);
        }
    
    }
    private static Document getDocument(String file) 
    {
        try 
        {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            factory.setIgnoringComments(true);
            factory.setIgnoringElementContentWhitespace(true);
            DocumentBuilder builder = factory.newDocumentBuilder();
            return builder.parse(file);
        } 
        catch (Exception e) 
        {
            return null;
        }
    }
    
    public static void copyFile(File in, File out) throws IOException {     // copy the file for a backup
        FileChannel inChannel = new FileInputStream(in).getChannel();
        FileChannel outChannel = new FileOutputStream(out).getChannel();
        inChannel.transferTo(0, inChannel.size(), outChannel);
    }
      protected void processWindowEvent(WindowEvent e)             // for pressing the "x" in the top right corner
 {
        if(e.getID()==WindowEvent.WINDOW_CLOSING)
  {

  if(JOptionPane.showConfirmDialog(null, "<html><body>Do you really want to close the program?<body><html>"   
     , "WARNING",
     JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
   {
    super.processWindowEvent(e);
                                System.exit(0);
                        }
                }
    }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btn_exit1;
    private javax.swing.JButton btn_return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taText;
    // End of variables declaration//GEN-END:variables
}
